name: create dev tag
on:
  repository_dispatch
jobs:
  build:
    name: Create prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: YYYYMMDD-HHmm
          utcOffset: "+09:00"
      - name: Create Release
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: prod-${{ steps.current-time.outputs.formattedTime }}
